export const authconstants={
        LOGINREQUEST:"LOGINREQUEST",
        LOGINFAILURE:"LOGINFAILURE",
        LOGINSUCCESS:"LOGINSUCCESS",

        LOGOUTREQUEST:"LOGOUTREQUEST",
        LOGOUTSUCCESS:"LOGOUTSUCCESS",
        LOGOUTFAILURE:"LOGOUTFAILURE"
}

export const userconstants={
        USERREGREQUEST:"USERREGREQUEST",
        USERREGSUCCESS:"USERREGSUCCESS",
        USERREGFAILURE:"USERREGFAILURE"
}

export const categoryconstants={
        GETALLCATEGORYREQUEST:"GETALLCATEGORYREQUEST",
        GETALLCATEGORYFAILURE:"GETALLCATEGORYFAILURE",
        GETALLCATEGORYSUCCESS:"GETALLCATEGORYSUCCESS",

        ADDNEWCATEGORYREQUEST:"ADDNEWCATEGORYREQUEST",
        ADDNEWCATEGORYFAILURE:"ADDNEWCATEGORYFAILURE",
        ADDNEWCATEGORYSUCCESS:"ADDNEWCATEGORYSUCCESS",

        UPDATECATEGORIESSUCCESS:"UPDATECATEGORIESSUCCESS",
        UPDATECATEGORIESFAILURE:"UPDATECATEGORIESFAILURE",
        UPDATECATEGORIESREQUEST:"UPDATECATEGORIESREQUEST",

        DELETECATEGORIESREQUEST:"DELETECATEGORIESREQUEST",
        DELETECATEGORIESSUCCESS:"DELETECATEGORIESSUCCESS",
        DELETECATEGORIESFAILURE:"DELETECATEGORIESFAILURE",
}

export const productconstants={
        GETALLPRODUCTREQUEST:"GETALLPRODUCTREQUEST",
        GETALLPRODUCTSUCCESS:"GETALLPRODUCTSUCCESS",
        GETALLPRODUCTFAILURE:"GETALLPRODUCTFAILURE"
}

export const initialdataconstants={
        GETALLINITIALDATAREQUEST:"GETALLINITIALDATAREQUEST",
        GETALLINITIALDATASUCCESS:"GETALLINITIALDATASUCCESS",
        GETALLINITIALDATAFAILURE:"GETALLINITIALDATAFAILURE"
}

export const pageconstants={
        CREATEPAGEREQUEST:"CREATEPAGEREQUEST",
        CREATEPAGESUCCESS:"CREATEPAGESUCCESS",
        CREATEPAGEFAILURE:"CREATEPAGEFAILURE"
}