
export const categoryconstants={
        GETALLCATEGORYREQUEST:"GETALLCATEGORYREQUEST",
        GETALLCATEGORYFAILURE:"GETALLCATEGORYFAILURE",
        GETALLCATEGORYSUCCESS:"GETALLCATEGORYSUCCESS",
        ADDNEWCATEGORYREQUEST:"ADDNEWCATEGORYREQUEST",
        ADDNEWCATEGORYFAILURE:"ADDNEWCATEGORYFAILURE",
        ADDNEWCATEGORYSUCCESS:"ADDNEWCATEGORYSUCCESS",

}

export const productconstants={
        GETPRODUCTSUCCESS:"GETPRODUCTSUCCESS",
        GETPRODUCTREQUEST:"GETPRODUCTREQUEST",
        GETPRODUCTFAILURE:"GETPRODUCFAILURE",

        GETPRODPAGEREQUEST:"GETPRODPAGEREQUEST",
        GETPRODPAGESUCCESS:"GETPRODPAGESUCCESS",
        GETPRODPAGEFAILURE:"GETPRODPAGEFAILURE"
}

